#!/usr/bin/env bash
#
# check_env.sh — verify the environment is ready to run the pipeline.
#
# Checks:
#   - Python version (>= 3.10)
#   - All required packages (from requirements.txt)
#   - GPU / hardware detection
#   - Kaggle credentials (~/.kaggle/kaggle.json)
#   - Key data and model directories
#
# Run after activating your conda environment:
#   conda activate SSE691NLP
#   ./scripts/check_env.sh
#
# Exit code: 0 = all checks passed, 1 = one or more failures.
#
# Usage:
#   ./scripts/check_env.sh

# No set -e: we want to continue past failing checks and report them all.
set -uo pipefail

cd "$(dirname "$0")/.."

echo "=================================================================="
echo " SkillPostBERT — environment check"
echo "=================================================================="

issues=0

# ---- Python + packages (single interpreter call) -------------------------- #
echo ""
echo "[python]"

python - << 'PYEOF'
import sys, importlib

# Python version
vi = sys.version_info
ok = (vi.major, vi.minor) >= (3, 10)
mark = "[ok]  " if ok else "[FAIL]"
suffix = "" if ok else "  (need >= 3.10)"
print(f"  {mark} Python {vi.major}.{vi.minor}.{vi.micro}{suffix}")
issues = 0 if ok else 1

# Required packages
PACKAGES = [
    ("torch",        "torch"),
    ("transformers", "transformers"),
    ("accelerate",   "accelerate"),
    ("datasets",     "datasets"),
    ("evaluate",     "evaluate"),
    ("seqeval",      "seqeval"),
    ("pandas",       "pandas"),
    ("sklearn",      "scikit-learn"),
    ("matplotlib",   "matplotlib"),
    ("kaggle",       "kaggle"),
    ("yaml",         "pyyaml"),
]
for mod, pkg in PACKAGES:
    try:
        m = importlib.import_module(mod)
        ver = getattr(m, "__version__", "?")
        print(f"  [ok]   {pkg}: {ver}")
    except ImportError:
        print(f"  [FAIL] {pkg}  <-- pip install -r requirements.txt")
        issues += 1

# GPU / hardware
try:
    from src.utils import get_hardware_profile
    p = get_hardware_profile()
    dt, dn = p["device_type"], p["device_name"]
    if dt == "cpu":
        print(f"  [warn] GPU: {dn}  (training will be slow — see README GPU setup)")
    elif dt == "cuda":
        import torch
        print(f"  [ok]   GPU: {dn}  (CUDA {torch.version.cuda})")
    else:
        print(f"  [ok]   GPU: {dn}")
except Exception as e:
    print(f"  [warn] GPU check failed: {e}")

sys.exit(issues)
PYEOF

py_exit=$?
issues=$((issues + py_exit))

# ---- Kaggle credentials --------------------------------------------------- #
echo ""
echo "[kaggle]"

KAGGLE_FILE="$HOME/.kaggle/kaggle.json"
if [[ ! -f "$KAGGLE_FILE" ]]; then
  echo "  [FAIL] kaggle.json not found at ~/.kaggle/kaggle.json"
  echo "         See README Setup section or run ./scripts/setup_kaggle.sh"
  issues=$((issues + 1))
else
  # Validate the JSON has username and key fields
  if python -c "
import json, sys
try:
    c = json.load(open('$KAGGLE_FILE'))
    if c.get('username') and c.get('key'):
        print('  [ok]   kaggle.json present (user: ' + c['username'] + ')')
        sys.exit(0)
    print('  [FAIL] kaggle.json missing username or key fields')
    sys.exit(1)
except Exception as e:
    print(f'  [FAIL] kaggle.json is not valid JSON: {e}')
    sys.exit(1)
"; then
    :
  else
    issues=$((issues + 1))
  fi
fi

# ---- Data and model directories ------------------------------------------- #
echo ""
echo "[directories]"

# data/raw
if [[ ! -d "data/raw" ]]; then
  echo "  [warn] data/raw/ does not exist — will be created on first download"
else
  csv_count=$(find data/raw -name "*.csv" 2>/dev/null | wc -l | tr -d ' ')
  if [[ "$csv_count" -eq 0 ]]; then
    echo "  [warn] data/raw/ is empty — run ./scripts/run_part1.sh to download"
  else
    echo "  [ok]   data/raw/ — ${csv_count} CSV file(s) present"
  fi
fi

# data/processed
if [[ ! -d "data/processed" ]]; then
  echo "  [warn] data/processed/ does not exist — generated by run_part1.sh"
else
  if [[ -f "data/processed/corpus.jsonl" ]]; then
    echo "  [ok]   corpus.jsonl"
  else
    echo "  [warn] corpus.jsonl  (not yet generated)"
  fi
  if [[ -f "data/processed/gold.conll" ]]; then
    echo "  [ok]   gold.conll"
  else
    echo "  [warn] gold.conll  (not yet generated)"
  fi
fi

# models
if [[ ! -d "models" ]]; then
  echo "  [warn] models/ does not exist — generated by run_part1.sh (train step)"
else
  model_count=$(find models -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l | tr -d ' ')
  if [[ "$model_count" -eq 0 ]]; then
    echo "  [warn] models/ is empty — run ./scripts/run_part1.sh to train"
  else
    model_names=$(find models -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | paste -sd ',' | sed 's/,/, /g')
    echo "  [ok]   models/ — ${model_count} model(s): ${model_names}"
  fi
fi

# results (informational only)
if [[ -d "results" ]]; then
  result_count=$(find results -maxdepth 1 -type f 2>/dev/null | wc -l | tr -d ' ')
  if [[ "$result_count" -gt 0 ]]; then
    echo "  [ok]   results/ — ${result_count} file(s) present"
  fi
fi

# ---- Summary -------------------------------------------------------------- #
echo ""
echo "=================================================================="
if [[ "$issues" -eq 0 ]]; then
  echo " All checks passed. Environment is ready."
  echo " Run ./scripts/run_part1.sh to start the pipeline."
else
  echo " ${issues} issue(s) found. Resolve the [FAIL] items above before running."
fi
echo "=================================================================="

exit $((issues > 0 ? 1 : 0))
