#Requires -Version 5.1
# check_env.ps1 — verify the environment is ready to run the pipeline.
#
# Checks:
#   - Python version (>= 3.10)
#   - All required packages (from requirements.txt)
#   - GPU / hardware detection
#   - Kaggle credentials (~\.kaggle\kaggle.json)
#   - Key data and model directories
#
# Run after activating your conda environment:
#   conda activate SSE691NLP
#   .\scripts\check_env.ps1
#
# Exit code: 0 = all checks passed, 1 = one or more failures.
#
# Usage:
#   .\scripts\check_env.ps1

Set-Location (Split-Path $PSScriptRoot -Parent)

Write-Host "=================================================================="
Write-Host " SkillPostBERT -- environment check"
Write-Host "=================================================================="

$issues = 0

# ---- Python + packages (single interpreter call) -------------------------- #
Write-Host ""
Write-Host "[python]"

$pyScript = @'
import sys, importlib

# Python version
vi = sys.version_info
ok = (vi.major, vi.minor) >= (3, 10)
mark = "[ok]  " if ok else "[FAIL]"
suffix = "" if ok else "  (need >= 3.10)"
print(f"  {mark} Python {vi.major}.{vi.minor}.{vi.micro}{suffix}")
issues = 0 if ok else 1

# Required packages
PACKAGES = [
    ("torch",        "torch"),
    ("transformers", "transformers"),
    ("accelerate",   "accelerate"),
    ("datasets",     "datasets"),
    ("evaluate",     "evaluate"),
    ("seqeval",      "seqeval"),
    ("pandas",       "pandas"),
    ("sklearn",      "scikit-learn"),
    ("matplotlib",   "matplotlib"),
    ("kaggle",       "kaggle"),
    ("yaml",         "pyyaml"),
]
for mod, pkg in PACKAGES:
    try:
        m = importlib.import_module(mod)
        ver = getattr(m, "__version__", "?")
        print(f"  [ok]   {pkg}: {ver}")
    except ImportError:
        print(f"  [FAIL] {pkg}  <-- pip install -r requirements.txt")
        issues += 1

# GPU / hardware
try:
    from src.utils import get_hardware_profile
    p = get_hardware_profile()
    dt, dn = p["device_type"], p["device_name"]
    if dt == "cpu":
        print(f"  [warn] GPU: {dn}  (training will be slow — see README GPU setup)")
    elif dt == "cuda":
        import torch
        print(f"  [ok]   GPU: {dn}  (CUDA {torch.version.cuda})")
    else:
        print(f"  [ok]   GPU: {dn}")
except Exception as e:
    print(f"  [warn] GPU check failed: {e}")

sys.exit(issues)
'@

python -c $pyScript
$pyExitCode = $LASTEXITCODE
if ($pyExitCode -ne 0) { $issues += $pyExitCode }

# ---- Kaggle credentials --------------------------------------------------- #
Write-Host ""
Write-Host "[kaggle]"

$kaggleFile = Join-Path $HOME ".kaggle\kaggle.json"
if (-not (Test-Path $kaggleFile)) {
    Write-Host "  [FAIL] kaggle.json not found at ~\.kaggle\kaggle.json"
    Write-Host "         See README Setup section or run .\scripts\setup_kaggle.ps1"
    $issues++
} else {
    try {
        $creds = Get-Content $kaggleFile -Raw | ConvertFrom-Json
        if ($creds.username -and $creds.key) {
            Write-Host "  [ok]   kaggle.json present (user: $($creds.username))"
        } else {
            Write-Host "  [FAIL] kaggle.json exists but is missing 'username' or 'key' fields"
            $issues++
        }
    } catch {
        Write-Host "  [FAIL] kaggle.json exists but is not valid JSON"
        $issues++
    }
}

# ---- Data and model directories ------------------------------------------- #
Write-Host ""
Write-Host "[directories]"

# data/raw
$rawDir = "data\raw"
if (-not (Test-Path $rawDir)) {
    Write-Host "  [warn] data\raw\ does not exist — will be created on first download"
} else {
    $csvFiles = @(Get-ChildItem $rawDir -Filter "*.csv" -Recurse -ErrorAction SilentlyContinue)
    if ($csvFiles.Count -eq 0) {
        Write-Host "  [warn] data\raw\ is empty — run .\scripts\run_part1.ps1 to download"
    } else {
        Write-Host "  [ok]   data\raw\ — $($csvFiles.Count) CSV file(s) present"
    }
}

# data/processed
$corpusFile = "data\processed\corpus.jsonl"
$goldConll  = "data\processed\gold.conll"
$goldJsonl  = "data\processed\gold.jsonl"
if (-not (Test-Path "data\processed")) {
    Write-Host "  [warn] data\processed\ does not exist — generated by run_part1.ps1"
} else {
    $corpusMark = if (Test-Path $corpusFile) { "[ok]  " } else { "[warn]" }
    $corpusNote = if (Test-Path $corpusFile) { "" }       else { "  (not yet generated)" }
    Write-Host "  $corpusMark corpus.jsonl$corpusNote"

    $goldMark = if (Test-Path $goldConll) { "[ok]  " } else { "[warn]" }
    $goldNote = if (Test-Path $goldConll) { "" }       else { "  (not yet generated)" }
    Write-Host "  $goldMark gold.conll$goldNote"
}

# models
$modelDir = "models"
if (-not (Test-Path $modelDir)) {
    Write-Host "  [warn] models\ does not exist — generated by run_part1.ps1 (train step)"
} else {
    $modelDirs = @(Get-ChildItem $modelDir -Directory -ErrorAction SilentlyContinue)
    if ($modelDirs.Count -eq 0) {
        Write-Host "  [warn] models\ is empty — run .\scripts\run_part1.ps1 to train"
    } else {
        Write-Host "  [ok]   models\ — $($modelDirs.Count) model(s): $($modelDirs.Name -join ', ')"
    }
}

# results
$resultsDir = "results"
if (Test-Path $resultsDir) {
    $resultFiles = @(Get-ChildItem $resultsDir -File -ErrorAction SilentlyContinue)
    if ($resultFiles.Count -gt 0) {
        Write-Host "  [ok]   results\ — $($resultFiles.Count) file(s) present"
    }
}

# ---- Summary -------------------------------------------------------------- #
Write-Host ""
Write-Host "=================================================================="
if ($issues -eq 0) {
    Write-Host " All checks passed. Environment is ready."
    Write-Host " Run .\scripts\run_part1.ps1 to start the pipeline."
} else {
    Write-Host " $issues issue(s) found. Resolve the [FAIL] items above before running."
}
Write-Host "=================================================================="

exit ([Math]::Min($issues, 1))
